name: Lint, Test, Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Set commit range variables
        run: |
          echo "PR_HEAD=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          echo "PR_BASE=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV

      - name: Conventional commit check
        run: npx commitlint --from $PR_BASE --to $PR_HEAD

      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Test
        run: npm test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: truongtrongtin/learn-nestjs:latest
          cache-from: type=registry,ref=truongtrongtin/learn-nestjs:buildcache
          cache-to: type=registry,ref=truongtrongtin/learn-nestjs:buildcache,mode=max

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/learn-nestjs

            docker run --rm \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v "$PWD:$PWD" \
              -w="$PWD" \
              docker/compose pull -q nest

            docker run --rm \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v "$PWD:$PWD" \
              -w="$PWD" \
              docker/compose up -d

            docker image prune -f

            docker exec nest node dist/migrate
